# Generated by Django 5.0.6 on 2024-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_demon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='Cookie', max_length=20),
            preserve_default=False,
        ),
    ]
