# Generated by Django 5.0.6 on 2024-05-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer_demon', '0003_alter_menuitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='soul_flavor',
        ),
    ]
