# Generated by Django 5.0.6 on 2024-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_demon', '0004_remove_customer_birthday_remove_customer_soul_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_total',
            field=models.FloatField(default=0),
        ),
    ]
